export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'workspace',
    path: '/workspace',
    title: '工作空间',
    requiresAuth: true,
    componentPath: '/workspace/index.vue',
    id: 1,
    pid: null,
    hide: true,
  },
  {
    name: 'appstore',
    path: '/appstore',
    title: '应用商店',
    requiresAuth: true,
    componentPath: '/appstore/index.vue',
    id: 9,
    pid: null,
  },
  {
    name: 'workspace-member',
    path: '/workspace/:id',
    title: '工作空间成员管理',
    requiresAuth: true,
    componentPath: '/workspace/member.vue',
    id: 11,
    pid: null,
    hide: true,
  },
  {
    name: 'agent',
    path: '/agent',
    title: '智能体',
    requiresAuth: true,
    componentPath: '/agent/index.vue',
    id: 2,
    pid: null,
  },
  {
    name: 'model',
    path: '/model',
    title: '模型',
    requiresAuth: true,
    componentPath: '/model/index.vue',
    id: 3,
    pid: null,
  },
  {
    name: 'tool',
    path: '/tool',
    title: '工具',
    requiresAuth: true,
    componentPath: '/tool/index.vue',
    id: 4,
    pid: null,
  },
  {
    name: 'database',
    path: '/database',
    title: '数据库',
    requiresAuth: true,
    componentPath: '/database/index.vue',
    id: 5,
    pid: null,
  },
  {
    name: 'rag',
    path: '/rag',
    title: 'RAG',
    requiresAuth: true,
    componentPath: '/rag/index.vue',
    id: 6,
    pid: null,
  },
  {
    name: 'faq',
    path: '/faq',
    title: 'FAQ',
    requiresAuth: true,
    componentPath: '/faq/index.vue',
    id: 7,
    pid: null,
  },
  {
    name: 'mcp',
    path: '/mcp',
    title: 'MCP',
    requiresAuth: true,
    componentPath: '/mcp/index.vue',
    id: 8,
    pid: null,
  },
  {
    name: 'userCenter',
    path: '/user-center',
    title: '个人中心',
    requiresAuth: true,
    hide: true,
    icon: 'carbon:user-avatar-filled-alt',
    componentPath: '/build-in/user-center/index.vue',
    id: 999,
    pid: null,
  },
  {
    name: 'user',
    path: '/user',
    title: '用户管理',
    requiresAuth: true,
    componentPath: '/user/index.vue',
    id: 10,
    pid: null,
    roles: ['superuser'],
    order: 100,
    hide: true,
  },
]
